pod 'Masonry', '~> 0.6.1'
pod 'AFNetworking', '~> 2.3.1'
pod 'FMDB', '~> 2.5'
pod 'SVProgressHUD', '~> 1.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MJRefresh', '~> 2.4.4'
pod 'KxMenu'
pod 'Bugly'
pod 'RongCloudIMKit'
pod 'IQKeyboardManager'
